<?php

/**
 * @file
 * Contains jcc_admin.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function jcc_admin_field_widget_entity_reference_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {

  // Hide the "Add To Hero Nav?" checkbox for nested Paragraphs.
  if (!empty($element['subform']['field_create_anchor'])) {
    if (!empty($element['subform']['field_create_anchor']['widget']['#field_parents'])) {
      $element['subform']['field_create_anchor']['#access'] = false;
    }
  }

  // When a Postcard is nested, prevent an h2 level header from being used.
  if (!empty($element['subform']['field_header']) && $element['subform']['field_header']['widget']['#bundle'] == 'postcard') {
    if (!empty($element['subform']['field_header']['widget']['#field_parents'])) {
      unset($element['subform']['field_header']['widget']['#options']['h2']);
      $element['subform']['field_header']['#disabled'] = true;
    }
  }
}
