<?php

/**
 * @file
 * Contains jcc_datefinder.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jcc_datefinder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the srl_date_calculator module.
    case 'help.page.srl_date_calculator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a configurable component type that allows a user to enter a date, then calculates important future dates based on the configuration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implments hook_preprocess_HOOK().
 */
function jcc_datefinder_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];

  if ($paragraph->getType() == 'datefinder') {

    // Don't add form or library if on the edit form, to prevent ajax issues.
    if (\Drupal::routeMatch()->getRouteName() != 'entity.node.edit_form') {

      // Load form with paragraph entity.
      $form = \Drupal::formBuilder()->getForm('Drupal\jcc_datefinder\Form\JCCDateFinderForm', $paragraph);

      $variables['jcc_datefinder_form'] = $form;
    }
  }
}
