<?php

/**
 * @file
 * Contains jcc_datefinder.module.
 */

/**
 * Implments hook_preprocess_HOOK().
 */
function jcc_datefinder_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];

  if ($paragraph->getType() == 'datefinder') {

    // Don't add form or library if on the edit form, to prevent ajax issues.
    if (\Drupal::routeMatch()->getRouteName() != 'entity.node.edit_form') {

      // Load form with paragraph entity.
      $form = \Drupal::formBuilder()->getForm('Drupal\jcc_datefinder\Form\JCCDateFinderForm', $paragraph);

      $variables['jcc_datefinder_form'] = $form;
    }
  }
}
