<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\xlsx\Event\XlsxEventType;
use Drupal\xlsx\Event\XlsxEntityEvent;
use Drupal\xlsx\Entity\FormThumbnail;

/**
 * Implements hook_entity_update().
 */
function xlsx_entity_update(EntityInterface $entity) {
  $event_type = XlsxEventType::UPDATE_ENTITY;
  $dispatcher = \Drupal::service('event_dispatcher')
    ->dispatch($event_type, new XlsxEntityEvent($event_type, $entity));
}

/**
 * Implements hook_entity_delete().
 */
function xlsx_entity_delete(EntityInterface $entity) {
  $event_type = XlsxEventType::DELETE_ENTITY;
  $dispatcher = \Drupal::service('event_dispatcher')
    ->dispatch($event_type, new XlsxEntityEvent($event_type, $entity));

  \Drupal::database()->delete('xlsx_entity_mapping')
    ->condition('entity_type', $entity->getEntityTypeId() . ':' . $entity->bundle())
    ->condition('entity_id', $entity->id())
    ->execute();
}

/**
 * Implements hook_entity_delete().
 */
function xlsx_file_delete(EntityInterface $entity) {
  if ($e = FormThumbnail::load($entity->id())) {
    $e->delete();
  }
}
