<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\xlsx\Event\XlsxEventType;
use Drupal\xlsx\Event\XlsxEntityEvent;

/**
 * Implements hook_entity_update().
 */
function xlsx_entity_update(EntityInterface $entity) {
  $event_type = XlsxEventType::UPDATE_ENTITY;
  $dispatcher = \Drupal::service('event_dispatcher')
    ->dispatch($event_type, new XlsxEntityEvent($event_type, $entity));
}

/**
 * Implements hook_entity_delete().
 */
function xlsx_entity_delete(EntityInterface $entity) {
  $event_type = XlsxEventType::DELETE_ENTITY;
  $dispatcher = \Drupal::service('event_dispatcher')
    ->dispatch($event_type, new XlsxEntityEvent($event_type, $entity));
}
