_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'key.key.*'
  - 'webform.webform.*'
  - tmgmt.settings
  - recaptcha.settings
  - 'tmgmt.translator.*'
  - tmgmt_memsource.settings
