_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  access_unpublished: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  advagg: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  allowed_formats: 0
  anchor_link: 0
  automated_cron: 0
  ban: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  cc: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_templates: 0
  color: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datalayer: 0
  datetime: 0
  dblog: 0
  default_content: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_clone: 0
  entity_embed: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  facets: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  fillpdf: 0
  filter: 0
  fixed_block_content: 0
  focal_point: 0
  google_tag: 0
  hal: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  insert_view_adv: 0
  jcc_autocomplete_helper: 0
  jcc_boilerplate: 0
  jcc_chatbot: 0
  jcc_datefinder: 0
  jcc_forms: 0
  jcc_twig: 0
  jsonapi: 0
  jsonapi_extras: 0
  key: 0
  language: 0
  link: 0
  linkit: 0
  locale: 0
  login_emailusername: 0
  markup: 0
  maxlength: 0
  media: 0
  media_entity_browser: 0
  media_library: 0
  media_text: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_pinterest: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  module_filter: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  quicklink: 0
  r4032login: 0
  rabbit_hole: 0
  range: 0
  rebuild_cache_access: 0
  recaptcha: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  rest: 0
  restui: 0
  rh_media: 0
  rh_node: 0
  rh_taxonomy: 0
  role_delegation: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_exclude: 0
  search_api_exclude_entity: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  sendgrid_integration: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  simple_sitemap: 0
  smart_trim: 0
  srl_court_finder: 0
  srl_custom: 0
  srl_errors: 0
  srl_ga_gtm: 0
  srl_updates: 0
  srl_webform: 0
  srl_webform_submission_finder: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tmgmt: 0
  tmgmt_config: 0
  tmgmt_content: 0
  tmgmt_file: 0
  tmgmt_memsource: 0
  token: 0
  toolbar: 0
  tooltip: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ajax_history: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_jqueryui_buttons: 0
  webform_rest: 0
  webform_translation_permissions: 0
  webform_ui: 0
  workbench: 0
  workflows: 0
  xlsx: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  jcc_admin: 20
  mega: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  atrium: 0
profile: mega
