_core:
  default_config_hash: dIZsh-f5gE1BcuZjI3nIz5gsss2nfMynKKcVFw77a1s
uri: 'public:/'
compact_snippet: true
include_file: true
rebuild_snippets: true
flush_snippets: false
debug_output: false
_default_container:
  container_id: ''
  hostname: www.googletagmanager.com
  data_layer: dataLayer
  include_classes: false
  whitelist_classes: |-
    google
    nonGooglePixels
    nonGoogleScripts
    nonGoogleIframes
  blacklist_classes: |-
    customScripts
    customPixels
  include_environment: false
  environment_id: ''
  environment_token: ''
  path_toggle: 'exclude listed'
  path_list: |-
    /admin*
    /batch*
    /node/add*
    /node/*/edit
    /node/*/delete
    /user/*/edit*
    /user/*/cancel*
  role_toggle: 'exclude listed'
  role_list: {  }
  status_toggle: 'exclude listed'
  status_list: ''
