<?php

/**
 * @file
 * srl_webform.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformEntityStorage;

/**
 * Implements hook_webform_element_default_properties_alter().
 */
function srl_webform_webform_element_default_properties_alter(array &$properties, array &$definition) {
  if($definition['id'] == 'webform_wizard_page') {
    $properties['hide_submit'] = false;
  }
}

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
function srl_webform_webform_element_configuration_form_alter(&$form, FormStateInterface $form_state) {

  /** @var Drupal\webform_ui\Form\WebformUiElementEditForm $form_object */
  $form_object = $form_state->getFormObject();
  $element_plugin = $form_object->getWebformElementPlugin();
  $element_type = $element_plugin->getTypeName();

  if($element_type == 'webform_wizard_page') {
    $form['wizard_page']['hide_submit'] = [
      '#type' => 'checkbox',
      '#title' => t('Hide submit button'),
      '#description' => t("If checked, user will advance to the next page immediately after selecting an option. <b>Only use this option when the page has one element with two options.</b>"),
    ];
  }
}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 */
function srl_webform_webform_element_webform_wizard_page_alter(array &$element, FormStateInterface $form_state, array $context) {

  if (isset($element['#hide_submit']) && $element['#hide_submit'] == true ) {

    $element['#attached']['drupalSettings']['srl_webform']['id'] = $element['#webform'];
    $element['#attached']['library'][] = 'srl_webform/hideSubmit';

  }
}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 */
function srl_webform_webform_element_radios_alter(array &$element, FormStateInterface $form_state, array $context) {
  _srl_webform_set_wizard_attribute($element);
}

/**
 * Implements hook_webform_element_ELEMENT_TYPE_alter().
 */
function srl_webform_webform_element_checkboxes_alter(array &$element, FormStateInterface $form_state, array $context) {

  _srl_webform_set_wizard_attribute($element);
}

function _srl_webform_set_wizard_attribute(array &$element) {
  if(isset($element['#webform'])) {
    $webform_id = $element['#webform'];

    /** @var Drupal\webform\WebformEntityStorage $entity_manager */
    $entity_manager = \Drupal::entityTypeManager()->getStorage('webform');

    /** @var Drupal\webform\Entity\Webform $webform */
    $webform = $entity_manager->load($webform_id);
    $webform_elements = $webform->getElementsDecoded();

    // Apply attribute so it is available in form-element.html.twig.
    if ($webform_elements['options']['#type'] = 'webform_wizard_page') {
      $element['#attributes']['data-webform-wizard-page-element'] = 1;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function srl_webform_preprocess_webform_actions(&$variables) {

  // Apply to webform wizard pager.
  if ($variables['element']['#type'] == 'actions') {
    $webform_id_part = str_replace('_add_form', '', $variables['element']['#form_id']);
    $webform_id = str_replace('webform_submission_', '', $webform_id_part);

    /** @var Drupal\webform\WebformEntityStorage $entity_manager */
    $entity_manager = \Drupal::entityTypeManager()->getStorage('webform');

    /** @var Drupal\webform\Entity\Webform $webform */
    $webform = $entity_manager->load($webform_id);

    $variables['webform_url'] = $webform->toUrl();
  }
}
