<?php

/**
 * @file
 * Contains jcc_boilerplate.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Yaml;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function jcc_boilerplate_form_node_srl_howto_instruction_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Get user input array.
  $user_input = $form_state->getUserInput();

  if (isset($user_input['_triggering_element_value'])
    && ($user_input['_triggering_element_value'] == 'Add Boilerplate Steps')) {

    // Get and parse .yml.
    // @todo Handle multiple boilerplates.
    $module_handler = \Drupal::service('module_handler');
    $module_path = $module_handler->getModule('jcc_boilerplate')->getPath();

    // Count existing paragraphs and set to index 0.
    $paragraph_count = count($user_input["field_paragraphs"]);
    $paragraph_count = $paragraph_count - 1;

    // Count existing steps.
    $step_count = count($user_input["field_paragraphs"][0]["subform"]["field_steps"]);

    // Send boilerplate step values to Drupal fields.
    $boilerplate_text = Yaml::decode(file_get_contents($module_path .'/jcc_boilerplate.service.yml'));
    $boilerplate_steps = $boilerplate_text['steps'];
    foreach ($boilerplate_steps as $i => $step) {

      $field_names = [
        'description',
        'title_display',
        'details_link_text',
        'details'
      ];

      foreach ($field_names as $field_name) {

        if ($form["field_paragraphs"]["widget"][$paragraph_count]["subform"]["field_steps"]["widget"][$i + $step_count]["subform"]["field_" . $field_name]["widget"][0]["value"]["#type"] ==
        'textfield') {

          $form["field_paragraphs"]["widget"][$paragraph_count]["subform"]["field_steps"]["widget"][$i + $step_count]["subform"]["field_" . $field_name]["widget"][0]["value"]["#default_value"] = $step[$field_name];
        }

        else {
          $form["field_paragraphs"]["widget"][$paragraph_count]["subform"]["field_steps"]["widget"][$i + $step_count]["subform"]["field_" . $field_name]["widget"][0]["#default_value"] = $step[$field_name];
        }
      }
    }
  }
}
